<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- Code analysis -->
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Add your shared package versions here -->
  </ItemGroup>
</Project>
