<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Modules.Identity.Application\Modules.Identity.Application.csproj" />
    </ItemGroup>

</Project>
